workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    environment:
      xcode: latest
    scripts:
      - name: Build for iOS Simulator
        script: |
          xcodebuild -project Dayline.xcodeproj \
          -scheme DaylineApp \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO build
    artifacts:
      - build/Build/Products/Debug-iphonesimulator/*.app
